name: Node.js CI

on:
  push:
    branches: [ main, testing ]
  pull_request:
    branches: [ main, testing ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version: [ '14.x' ]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: web/vue-spa
        run: npm install

      - name: Run unit tests
        working-directory: web/vue-spa
        run: npm run test

      - name: Run end-to-end tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: web/vue-spa
          browser: chrome
